Создал Класс, который сохраняет в DB
vivelekostas/SuperWorkOganizer pull request #1
Opened 2019-03-25 10:03 UTC by vivelekostas

2019-03-25 10:56 UTC, Mavlyan requested changes
Бжжж

2019-03-25 10:56 UTC, Mavlyan commented on test/classes/TasksDBManager.php
> +        mysqli_insert_id($link);    //присваевает новой задаче id
@vivelekostas  Из документации:
"Функция mysqli_insert_id() возвращает ID, генерируемый запросом"

она ничего не присваивает

2019-03-25 10:56 UTC, Mavlyan commented on test/classes/TasksDBManager.php
> +}
Такую шляпу сразу удаляй. Это не милосердно по отношению к тому, кто будет ревьювить.

2019-03-25 10:56 UTC, Mavlyan commented on test/DB_Lesson/create_table.php
> +        `murcha` (
чо за мурча? :)

Метод создания таблицы встрой в класс ТаскДбМанагер. Типа "если нет такой таблицы - то создать её"

2019-03-25 11:01 UTC, vivelekostas commented on test/classes/TasksDBManager.php
> +        mysqli_insert_id($link);    //присваевает новой задаче id
Зануда, это одно и тоже по факту. А у меня понятнее описано)

2019-03-25 11:02 UTC, vivelekostas commented on test/classes/TasksDBManager.php
> +}
В смысле, какую шляпу? закоменченную копию кода?

2019-03-25 11:03 UTC, vivelekostas commented on test/DB_Lesson/create_table.php
> +        `murcha` (
Понял, постараюсь

2019-03-27 07:50 UTC, Mavlyan commented on test/classes/TasksDBManager.php
> +        mysqli_insert_id($link);    //присваевает новой задаче id
Не верно. Читай внимательно документацию

2019-03-27 12:25 UTC, vivelekostas commented on test/classes/TasksDBManager.php
> +        mysqli_insert_id($link);    //присваевает новой задаче id
Удалил её совсем

2019-03-27 12:26 UTC, vivelekostas commented on test/DB_Lesson/create_table.php
> +        `murcha` (
Добавил

2019-03-27 12:27 UTC, vivelekostas commented on test/classes/TasksDBManager.php
> +}
удаляю

2019-04-03 10:28 UTC, closed without merging