Удалена страя версия (mysqli); Классы переписаны под PDO; добавлен но…
vivelekostas/SuperWorkOganizer pull request #5
Opened 2019-04-25 09:27 UTC by vivelekostas

…вый исполнительный файл testIndex

2019-04-25 11:35 UTC, Mavlyan requested changes

2019-04-25 11:35 UTC, Mavlyan commented on test/classes/TasksDBManager.php
> + * To change this license header, choose License Headers in Project Properties.
pls remove useless comments like license header

2019-04-25 11:35 UTC, Mavlyan commented on test/classes/TasksDBManager.php
> +        $createTableSql = null;
поясни зочем эта строка. Удалять не надо, просто поясни

2019-04-25 11:35 UTC, Mavlyan commented on test/classes/TasksDBManager.php
> +    public function Display($newTask) {
названия методов в одном стиле должны быть. Большая буква детектед

2019-04-25 11:35 UTC, Mavlyan commented on test/classes/TasksDBManager.php
> +    public function Display($newTask) {
На мойвзгляд это бесполезный метод. особенно в классе работы с БД. К Бд он не имеет отношения. А вот если бы ты передавал в этотм метод ID задачи - то был бы смысл в нем: получить из БД задачу и отобразить инфу о ней

2019-04-25 11:35 UTC, Mavlyan commented on test/classes/TasksDBManager.php
> +        $showAllQuery = "SELECT * FROM `tasks`;";
Имхо, назван  неверно. Название и содержание расходятся. Написано `show` а на самом деле метод ничего не показывает,Ю просто возвращает массив с данными.
предлагаю переименовать в `getAllTasks()`

2019-04-25 11:35 UTC, Mavlyan commented on test/classes/TasksDBManager.php
> +    public function showAllActualTasks() {
то же самое что и предыдущий метод

2019-04-25 11:35 UTC, Mavlyan commented on test/classes/TasksDBManager.php
> +    public function showAllFinishedTasks() {
см предыдущ комент

2019-04-25 11:35 UTC, Mavlyan commented on test/classes/TasksDBManager.php
> +    public function allActualSimple() {
название метода начинается с глагола. Здесь уместен getBlahBlahBlah()

2019-04-25 11:35 UTC, Mavlyan commented on test/classes/TasksDBManager.php
> +    public function allWeekly() {
то же самое

2019-04-25 11:35 UTC, Mavlyan commented on test/classes/TasksDBManager.php
> +    public function allSimple() {
то же самое

2019-04-25 11:35 UTC, Mavlyan commented on test/classes/TasksDBManager.php
> +    public function allComplex() {
то же самое

2019-04-25 11:35 UTC, Mavlyan commented on test/testIndex.php
> + 'Список всех актуальных задачь - 2' . PHP_EOL .
задач - без мягкого знака :trollface:

2019-04-25 11:35 UTC, Mavlyan commented on test/testIndex.php
> +    $newTask = new СreateTask($name, $category, $status);
1. в пул реквесте нет такого класса. Видимо он провтыкан
2. В данном контексте класс не может называться CreateTask. Потому что  созданием таски занимается другой класс - менеджер. А этот класс просто содержит данные. Никаких операций над ними не производит. Поэтому название, как говорят, не семантическое. Вводит в заблуждение
3. Ты где-то рассказыал, что бросается Exception если некорректный ввод. Я не нашел ни эксепшна, ни его обработки.

2019-05-03 11:46 UTC, vivelekostas commented on test/classes/TasksDBManager.php
> + * To change this license header, choose License Headers in Project Properties.
bereit!

2019-05-03 11:46 UTC, vivelekostas commented on test/classes/TasksDBManager.php
> +        $createTableSql = null;
пояснил

2019-05-03 11:47 UTC, vivelekostas commented on test/classes/TasksDBManager.php
> +    public function Display($newTask) {
удалил и перенес в качестве функции в testIndex

2019-05-03 11:49 UTC, vivelekostas commented on test/classes/TasksDBManager.php
> +        $showAllQuery = "SELECT * FROM `tasks`;";
bereit!

2019-05-03 11:51 UTC, vivelekostas commented on test/classes/TasksDBManager.php
> +    public function showAllActualTasks() {
bereit!

2019-05-03 11:54 UTC, vivelekostas commented on test/classes/TasksDBManager.php
> +    public function allWeekly() {
bereit!

2019-05-03 11:56 UTC, vivelekostas commented on test/classes/TasksDBManager.php
> +    public function allSimple() {
bereit!

2019-05-03 11:56 UTC, vivelekostas commented on test/classes/TasksDBManager.php
> +    public function allComplex() {
bereit!

2019-05-03 12:00 UTC, vivelekostas commented on test/testIndex.php
> + 'Список всех актуальных задачь - 2' . PHP_EOL .
bereit!

2019-05-03 12:01 UTC, vivelekostas commented on test/testIndex.php
> +    $newTask = new СreateTask($name, $category, $status);
bereit!

2019-05-03 12:17 UTC, vivelekostas commented on test/testIndex.php
> +    $newTask = new СreateTask($name, $category, $status);
Exception - теперь божественен!))) Благодаря тебе!

2019-05-03 14:52 UTC, Mavlyan reviewed
На пересдачу!

2019-05-03 14:52 UTC, Mavlyan commented on test/classes/Task.php
> +        //TODO: А если status==jopa ?
Ну йоперный балет жеж! Братан ну ё маё !

2019-05-03 14:52 UTC, Mavlyan commented on test/classes/Task.php
> +//        if (!(($category == 'weekly') or ( $category == 'simple') or ( $category == 'complex'))) {
эй ты определись чо ты хошь, да?

2019-05-03 14:52 UTC, Mavlyan commented on test/classes/TasksDBManager.php
> +    public function allSimple() {
дык переименуй жеж!

2019-05-03 14:52 UTC, Mavlyan commented on test/classes/TasksDBManager.php
> +    public function allComplex() {
Что allComplex? 
Гет наверное ол комплекс или что ты имел ввиду?

2019-05-03 14:52 UTC, Mavlyan commented on test/testIndex.php
> + * To change this license header, choose License Headers in Project Properties.
Чо за хедер опять?

2019-05-03 14:52 UTC, Mavlyan commented on test/testIndex.php
> + * To change this license header, choose License Headers in Project Properties.
Наш шеф заставляет нас самим проверять свои пул реквесты после создания - мы многие ошибки способны заметить сами свежим взглядом. 
Предлагаю такую же практику ввести: просматривай пул реквест на гитхабе внимательно прежде чем проинформировать меня о необходимости мержить

Спасибо

2019-05-03 14:52 UTC, Mavlyan requested changes
На пересдачу!

2019-08-15 10:10 UTC, merged